from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
MODELS_DIR = PROJECT_ROOT / "models"

DUCKDB_PATH = RAW_DATA_DIR / "index.duckdb"

#RAW_DATA_DIR
RAW_RUREVIEWS_PATH = RAW_DATA_DIR / "RuReviews.csv"
WB_RAW_PATH = RAW_DATA_DIR / "raw_WB.csv"

#PROCESSED_DATA_DIR
WB_CLEANED_PATH = PROCESSED_DATA_DIR / "WB_cleaned.csv"
RUREVIEWS_PATH = PROCESSED_DATA_DIR / "RuReviews_cleaned.csv"
RUREVIEWS_WB_BALANCED_FOR_TRAIN_PATH = PROCESSED_DATA_DIR / "RuReviews_WB_balanced_for_train.csv"
RUREVIEWS_WB_BALANCED_FOR_VALIDATION_PATH = PROCESSED_DATA_DIR / "RuReviews_WB_balanced_for_validation.csv"
RUREVIEWS_FOR_TEST_PATH = PROCESSED_DATA_DIR / "RuReviews_for_test.csv"
WB_FOR_TEST_PATH = PROCESSED_DATA_DIR / "WB_for_test.csv"
RUREVIEWS_AND_WB_FOR_TEST_PATH = PROCESSED_DATA_DIR / "RuReviews_and_WB_for_test.csv"

